export const Pregnant = require('../animations/pregnant.json');
export const NewMom = require('../animations/mom.json');
export const Settingup = require('../animations/on3.json');
export const On1 = require('../animations/on1.json');
export const Happy = require('../animations/mood1.json'); //Happy
export const Calm = require('../animations/mood2.json'); //calm
export const Sad = require('../animations/mood3.json'); //sad
export const Hopefull = require('../animations/mood4.json'); //hopefull
export const Fearfull = require('../animations/mood5.json'); // fearfull
export const Angry = require('../animations/mood7.json'); //angry
export const Surprised = require('../animations/mood6.json'); //surpise
export const Disgusted = require('../animations/mood8.json'); //disgusted
export const Bubble = require('../animations/bubble.json');
